name: Unit Testes

on: [pull_request]

jobs:
    test:
      name: Run React Tests
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        - name: Install react-scripts@5.0.1
          run: npm install react-scripts@latest --save-dev --legacy-peer-deps
            
        - name: Install Dependencies
          run: |
            npm install --save-dev @testing-library/react 
            npm install --legacy-peer-deps 

        - name: Run Tests
          run: npm test

        - name: Run ESLint
          run: npm run lint  